{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsedoff\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\tkinter\\__init__.py\", line 1948, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\nsedoff\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\tkinter\\__init__.py\", line 861, in callit\n",
      "    func(*args)\n",
      "  File \"C:\\Users\\nsedoff\\AppData\\Local\\Temp\\ipykernel_23980\\2739609997.py\", line 16, in delete_fruit\n",
      "    fruits.remove(fruit)\n",
      "ValueError: list.remove(x): x not in list\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsedoff\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\tkinter\\__init__.py\", line 1948, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\nsedoff\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\tkinter\\__init__.py\", line 861, in callit\n",
      "    func(*args)\n",
      "  File \"C:\\Users\\nsedoff\\AppData\\Local\\Temp\\ipykernel_23980\\2739609997.py\", line 16, in delete_fruit\n",
      "    fruits.remove(fruit)\n",
      "ValueError: list.remove(x): x not in list\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsedoff\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\tkinter\\__init__.py\", line 1948, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\nsedoff\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\tkinter\\__init__.py\", line 861, in callit\n",
      "    func(*args)\n",
      "  File \"C:\\Users\\nsedoff\\AppData\\Local\\Temp\\ipykernel_23980\\2739609997.py\", line 16, in delete_fruit\n",
      "    fruits.remove(fruit)\n",
      "ValueError: list.remove(x): x not in list\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsedoff\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\tkinter\\__init__.py\", line 1948, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\nsedoff\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\tkinter\\__init__.py\", line 861, in callit\n",
      "    func(*args)\n",
      "  File \"C:\\Users\\nsedoff\\AppData\\Local\\Temp\\ipykernel_23980\\2739609997.py\", line 16, in delete_fruit\n",
      "    fruits.remove(fruit)\n",
      "ValueError: list.remove(x): x not in list\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsedoff\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\tkinter\\__init__.py\", line 1948, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\nsedoff\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\tkinter\\__init__.py\", line 861, in callit\n",
      "    func(*args)\n",
      "  File \"C:\\Users\\nsedoff\\AppData\\Local\\Temp\\ipykernel_23980\\2739609997.py\", line 16, in delete_fruit\n",
      "    fruits.remove(fruit)\n",
      "ValueError: list.remove(x): x not in list\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsedoff\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\tkinter\\__init__.py\", line 1948, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\nsedoff\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\tkinter\\__init__.py\", line 861, in callit\n",
      "    func(*args)\n",
      "  File \"C:\\Users\\nsedoff\\AppData\\Local\\Temp\\ipykernel_23980\\2739609997.py\", line 16, in delete_fruit\n",
      "    fruits.remove(fruit)\n",
      "ValueError: list.remove(x): x not in list\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsedoff\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\tkinter\\__init__.py\", line 1948, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\nsedoff\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\tkinter\\__init__.py\", line 861, in callit\n",
      "    func(*args)\n",
      "  File \"C:\\Users\\nsedoff\\AppData\\Local\\Temp\\ipykernel_23980\\2739609997.py\", line 16, in delete_fruit\n",
      "    fruits.remove(fruit)\n",
      "ValueError: list.remove(x): x not in list\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsedoff\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\tkinter\\__init__.py\", line 1948, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\nsedoff\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\tkinter\\__init__.py\", line 861, in callit\n",
      "    func(*args)\n",
      "  File \"C:\\Users\\nsedoff\\AppData\\Local\\Temp\\ipykernel_23980\\2739609997.py\", line 16, in delete_fruit\n",
      "    fruits.remove(fruit)\n",
      "ValueError: list.remove(x): x not in list\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsedoff\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\tkinter\\__init__.py\", line 1948, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\nsedoff\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\tkinter\\__init__.py\", line 861, in callit\n",
      "    func(*args)\n",
      "  File \"C:\\Users\\nsedoff\\AppData\\Local\\Temp\\ipykernel_23980\\2739609997.py\", line 16, in delete_fruit\n",
      "    fruits.remove(fruit)\n",
      "ValueError: list.remove(x): x not in list\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsedoff\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\tkinter\\__init__.py\", line 1948, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\nsedoff\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\tkinter\\__init__.py\", line 861, in callit\n",
      "    func(*args)\n",
      "  File \"C:\\Users\\nsedoff\\AppData\\Local\\Temp\\ipykernel_23980\\2739609997.py\", line 16, in delete_fruit\n",
      "    fruits.remove(fruit)\n",
      "ValueError: list.remove(x): x not in list\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsedoff\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\tkinter\\__init__.py\", line 1948, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\nsedoff\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\tkinter\\__init__.py\", line 861, in callit\n",
      "    func(*args)\n",
      "  File \"C:\\Users\\nsedoff\\AppData\\Local\\Temp\\ipykernel_23980\\2739609997.py\", line 16, in delete_fruit\n",
      "    fruits.remove(fruit)\n",
      "ValueError: list.remove(x): x not in list\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsedoff\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\tkinter\\__init__.py\", line 1948, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\nsedoff\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\tkinter\\__init__.py\", line 861, in callit\n",
      "    func(*args)\n",
      "  File \"C:\\Users\\nsedoff\\AppData\\Local\\Temp\\ipykernel_23980\\2739609997.py\", line 16, in delete_fruit\n",
      "    fruits.remove(fruit)\n",
      "ValueError: list.remove(x): x not in list\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsedoff\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\tkinter\\__init__.py\", line 1948, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\nsedoff\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\tkinter\\__init__.py\", line 861, in callit\n",
      "    func(*args)\n",
      "  File \"C:\\Users\\nsedoff\\AppData\\Local\\Temp\\ipykernel_23980\\2739609997.py\", line 16, in delete_fruit\n",
      "    fruits.remove(fruit)\n",
      "ValueError: list.remove(x): x not in list\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsedoff\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\tkinter\\__init__.py\", line 1948, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\nsedoff\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\tkinter\\__init__.py\", line 861, in callit\n",
      "    func(*args)\n",
      "  File \"C:\\Users\\nsedoff\\AppData\\Local\\Temp\\ipykernel_23980\\2739609997.py\", line 16, in delete_fruit\n",
      "    fruits.remove(fruit)\n",
      "ValueError: list.remove(x): x not in list\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsedoff\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\tkinter\\__init__.py\", line 1948, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\nsedoff\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\tkinter\\__init__.py\", line 861, in callit\n",
      "    func(*args)\n",
      "  File \"C:\\Users\\nsedoff\\AppData\\Local\\Temp\\ipykernel_23980\\2739609997.py\", line 16, in delete_fruit\n",
      "    fruits.remove(fruit)\n",
      "ValueError: list.remove(x): x not in list\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsedoff\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\tkinter\\__init__.py\", line 1948, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\nsedoff\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\tkinter\\__init__.py\", line 861, in callit\n",
      "    func(*args)\n",
      "  File \"C:\\Users\\nsedoff\\AppData\\Local\\Temp\\ipykernel_23980\\2739609997.py\", line 16, in delete_fruit\n",
      "    fruits.remove(fruit)\n",
      "ValueError: list.remove(x): x not in list\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsedoff\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\tkinter\\__init__.py\", line 1948, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\nsedoff\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\tkinter\\__init__.py\", line 861, in callit\n",
      "    func(*args)\n",
      "  File \"C:\\Users\\nsedoff\\AppData\\Local\\Temp\\ipykernel_23980\\2739609997.py\", line 16, in delete_fruit\n",
      "    fruits.remove(fruit)\n",
      "ValueError: list.remove(x): x not in list\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsedoff\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\tkinter\\__init__.py\", line 1948, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\nsedoff\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\tkinter\\__init__.py\", line 861, in callit\n",
      "    func(*args)\n",
      "  File \"C:\\Users\\nsedoff\\AppData\\Local\\Temp\\ipykernel_23980\\2739609997.py\", line 16, in delete_fruit\n",
      "    fruits.remove(fruit)\n",
      "ValueError: list.remove(x): x not in list\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsedoff\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\tkinter\\__init__.py\", line 1948, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\nsedoff\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\tkinter\\__init__.py\", line 861, in callit\n",
      "    func(*args)\n",
      "  File \"C:\\Users\\nsedoff\\AppData\\Local\\Temp\\ipykernel_23980\\2739609997.py\", line 16, in delete_fruit\n",
      "    fruits.remove(fruit)\n",
      "ValueError: list.remove(x): x not in list\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsedoff\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\tkinter\\__init__.py\", line 1948, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\nsedoff\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\tkinter\\__init__.py\", line 861, in callit\n",
      "    func(*args)\n",
      "  File \"C:\\Users\\nsedoff\\AppData\\Local\\Temp\\ipykernel_23980\\2739609997.py\", line 16, in delete_fruit\n",
      "    fruits.remove(fruit)\n",
      "ValueError: list.remove(x): x not in list\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\nsedoff\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\tkinter\\__init__.py\", line 1948, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\nsedoff\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\tkinter\\__init__.py\", line 861, in callit\n",
      "    func(*args)\n",
      "  File \"C:\\Users\\nsedoff\\AppData\\Local\\Temp\\ipykernel_23980\\2739609997.py\", line 16, in delete_fruit\n",
      "    fruits.remove(fruit)\n",
      "ValueError: list.remove(x): x not in list\n"
     ]
    }
   ],
   "source": [
    "import tkinter as tk\n",
    "import random\n",
    "\n",
    "def create_fruit():\n",
    "    x = random.randint(50, 550)\n",
    "    y = random.randint(50, 550)\n",
    "    fruit_type = random.choice(fruit_images)\n",
    "    fruit = canvas.create_image(x, y, anchor=tk.CENTER, image=fruit_type)\n",
    "    fruits.append((fruit, (x, y)))\n",
    "    canvas.after(3000, delete_fruit, fruit)\n",
    "    # Планируем создание следующего фрукта\n",
    "    canvas.after(1000, create_fruit)\n",
    "\n",
    "def delete_fruit(fruit):\n",
    "    canvas.delete(fruit)\n",
    "    fruits.remove(fruit)\n",
    "\n",
    "def collect(event):\n",
    "    global score\n",
    "    x, y = event.x, event.y\n",
    "    for fruit, (fx, fy) in list(fruits):  # Используем копию списка, чтобы избежать изменений во время итерации\n",
    "        if fx - 25 < x < fx + 25 and fy - 25 < y < fy + 25:\n",
    "            canvas.delete(fruit)\n",
    "            fruits.remove((fruit, (fx, fy)))\n",
    "            score += 1\n",
    "            score_label.config(text=f\"Score: {score}\")\n",
    "            break\n",
    "\n",
    "root = tk.Tk()\n",
    "root.title(\"Собери фрукты\")\n",
    "\n",
    "canvas = tk.Canvas(root, width=600, height=600, bg='lightgreen')\n",
    "canvas.pack()\n",
    "\n",
    "# Загрузка измененных изображений фруктов\n",
    "apple_img = tk.PhotoImage(file=\"resized_apple.png\")\n",
    "banana_img = tk.PhotoImage(file=\"resized_banana.png\")\n",
    "orange_img = tk.PhotoImage(file=\"resized_orange.png\")\n",
    "\n",
    "fruit_images = [apple_img, banana_img, orange_img]\n",
    "fruits = []\n",
    "score = 0\n",
    "\n",
    "score_label = tk.Label(root, text=\"Score: 0\", font=(\"Arial\", 18))\n",
    "score_label.pack()\n",
    "\n",
    "canvas.bind(\"<Button-1>\", collect)\n",
    "\n",
    "# Начинаем создание фруктов\n",
    "create_fruit()\n",
    "\n",
    "root.mainloop()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
